import pytest
from Projeto_xirico.repositories.operator_repository import OperatorRepository
from Projeto_xirico.infra import InfraData
from Projeto_xirico import exc


@pytest.fixture
def repo(conector):
    infra=InfraData(conector)
    return OperatorRepository(conector)
    
    
@pytest.fixture
def dados():
    dados={'nome': 'umohau', 'identificacao': '83689772925', 'telefone': '852703882', 'email': 'muhauhara3@gmail.com', 'endereco': 'moamba, matadouro',
'senha':'muhau333',
'ADM':False, 'ativo':True}
    return dados
    
    
def test_insert_sucess(repo, dados):
    """
    given:
        a repository of operators 'repo' and dictionary `dados`.
            
    when:
        `insert` is called with new data.
            
    then:
        the `id` generated by `insert` must be 1,
         and the return of `search_id` must contain all data items.
    """
    id=repo.insert(dados)
    operador=repo.search_id(id)
    assert id==1
    assert all(item in operador.items() for item in dados.items())


def test_insert_duplicate(repo, dados):
    """
    given:
        a repository of operators `repo`.
    
    when:
        `insert` is called with data that has already been inserted before.
    
    then:
        `DuplicateError` must be raised.
    """
    repo.insert(dados)
    with pytest.raises(exc.DuplicateError):
        repo.insert(dados)                
        
        
def test_delete_sucess(repo, dados):
    """
    given:
        repositorio de operadores com ao menos um operador registrado.
        
    when:
        delete é chamado com o id do operador registrado.
        
    then:
        search_id deve levantar EntityNotFoundError.
    """
    id=repo.insert(dados)
    repo.delete(id) 
    with pytest.raises(exc.EntityNotFoundError):
        repo.search_id(id)
        
      
def test_delete_EntityNotFound(repo):
    id=999
    with pytest.raises(exc.EntityNotFoundError):
        repo.delete(id)
        
        
def test_update_with_id_sucess(repo, dados):
    dado={"nome":"jorge"}
    id=repo.insert(dados)
    repo.update(dado, id)
    operador=repo.search_id(id)
    assert dado.get("nome")==operador.get("nome")
    
    
def test_update_with_email(repo, dados):
    email=dados.get("email")
    dado={"nome":"cardoso"}
    id=repo.insert(dados)
    repo.update(dados_=dado, email=email)
    operador=repo.search_id(id)
    
    assert dado.get('nome')==operador.get('nome')
        
def test_reactivate_sucess(repo, dados):
    email=dados.get('email')
    id=repo.insert(dados)
    repo.delete(id)
    recup=repo.reactivate(id)
    operador= repo.search_id(id)
    
    assert recup is True
    assert all(item in operador.items() for item in  dados.items())        
    
        
def test_update_no_indentificators(repo):
    dado={"nome":"cardoso"}
    with pytest.raises(exc.IdentificatorError):
        repo.update(dado)
        
     
def test_search_all_sucess(repo, dados):
    repo.insert(dados)
    operadores=repo.search_all()
    assert isinstance(operadores, list)
    assert all(item in operadores[0].items() for item in dados.items())
    
    
def test_search_all_empty_table(repo):
    with pytest.raises(exc.EmptyTableError):
        repo.search_all()
        
        
def test_search_name(repo, dados):
    nome=dados.get("nome")
    repo.insert(dados)
    operadores=repo.search_name(nome)
    assert isinstance(operadores, list)
    assert all(item in operadores[0].items() for item in dados.items())
    
    
def test_search_name_entity_not_found(repo):   
    with pytest.raises(exc.EntityNotFoundError):
        repo.search_name("joao")
        
        
def test_search_email_sucess(repo, dados):
    email=dados.get('email')
    repo.insert(dados)
    operador=repo.search_email(email)
    assert isinstance(operador, dict)
    assert all(item in operador.items() for item in dados.items())
    
    
def test_search_email_entity_not_found(repo):
    with pytest.raises(exc.EntityNotFoundError):
        repo.search_email("teste@gmail.com")
        
        
def test_found_inactive_sucess(repo, dados):
    email=dados.get('email')
    id=repo.insert(dados)
    repo.delete(id)
    inativo=repo.found_inactive(email)
    assert isinstance(inativo, dict)
    assert inativo.get("ativo") ==False
    
    
def test_found_inactive_entity_not_found(repo, dados):
    email= dados.get("email")
    repo.insert(dados)
    with pytest.raises(exc.EntityNotFoundError):
        repo.found_inactive(email)
        
        
def test_get_password_sucess(repo, dados):
    email=dados.get('email')
    repo.insert(dados)
    senha=repo.get_password(email)
    assert senha==dados.get("senha")
    
        
def test_check_unique_sucess(repo,dados):
    resultado=repo.check_unique(dados)
    assert resultado is True            
    
       
def test_check_unique_fail(repo, dados):
    repo.insert(dados)
    with pytest.raises(exc.DuplicateError) as e:
        res=repo.check_unique(dados)
    assert "identificacao" in str(e)
    
    
def test_total_records(repo, dados):
    repo.insert(dados)
    assert repo.total_records ==1